### ISSUE TITLE
Frend.co features

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#54]
- [x] Improve build process in Gulp #55 
- [x] Add CSS linting #55 
- [x] Rework CSS styles #56 
- [x] Implement CriticalCSS to improve our PageSpeed ranking. #58 
- [x] SSL :arrow_up_small: #89 
- [x] Add comment header to JS dist files Gulp task. Reference component name, author and version number?
- [ ] Rewrite component docs and about page, improve the consistency between components. :arrow_up_small:
- [ ] Spec out new features for the component page - stats, revisions, history etc. :arrow_down_small:
- [ ] Look into writing a post about Frend, explaining the reasons behind the creation of it, how it works, where we see it heading in the future. Host on site or external? :arrow_down_small:
- [ ] Service Worker :arrow_down_small:
- [ ] ~~Improve code 'link buttons' contrast to meet a11y~~ (We can look into this when we update the design)

**Comment by thomasdigby** [comment]
Linting & Gulp implemented in #55

**Comment by thomasdigby** [comment]
Reworked CSS in #56

**Comment by thomasdigby** [comment]
Critical CSS (but not really) in #58

**Comment by thomasdigby** [comment]
For the new features on the component page we can access commit data through the [API](https://api.github.com/repos/frend/frend.co/commits) and pass a path to get the relevant component - [?path=_components/accordion](https://api.github.com/repos/frend/frend.co/commits?path=_components/accordion)

Looks like we're going to need that SSL to retrieve this data...

**Comment by thomasdigby** [comment]
SSL YO #89
